<?php

function lpu_spaces_menu() {
    $items = array();
    $items['space/%'] = array(
        'title'            => t('Private Space'),
        'description'      => 'redirect to private space',
        'access arguments' => array('access content'),
        'page callback'    => 'lpu_spaces_set',
        'page arguments'   => array(1),
        'type'             => MENU_NORMAL_ITEM,
    );
    return $items;
}


function lpu_spaces_preprocess_html(&$vars) {
    if (drupal_is_front_page() && lpu_spaces_get()) {
        $_SESSION['lpu_current_space'] = 0;
        drupal_goto();
    }
}



function lpu_spaces_set($__space = NULL) {
    global $user;


    $_SESSION['lpu_current_space'] = $__space;
    // d($LPU_SPACES['current_space']);

    if (lpu_spaces_get()) {
        $u = user_load($user->uid);
        $spacesValues = field_get_items('user', $u, 'field_espaces');
        $spaces = array();
        if (is_array($spacesValues)) {
            foreach($spacesValues as $spacesValue) {
                if (isset($spacesValue['value'])) {
                    $spaces[] = $spacesValue['value'];
                }
            }
        }
        if (! (is_array($spaces) && in_array(lpu_spaces_get(), $spaces)) ) {
            $_SESSION['lpu_current_space'] = 0;
            lpu_spaces__user_logout();
            drupal_goto('user/login');
            exit;
        }
    }
    $nodeQuery = new EntityFieldQuery();
    $nodes = $nodeQuery
        ->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'home')
        ->fieldCondition('field_espaces', 'value', $_SESSION['lpu_current_space'], '=')
        ->addMetaData('account', user_load(1)) // Run the query as user 1.
        ->execute()
    ;
    if ( isset($nodes['node']) && count($nodes['node']) ) {
        $nids = array_keys($nodes['node']);
        drupal_goto('node/'.$nids[0]);
        exit;
    }
    drupal_goto('<front>');
}

function lpu_spaces_get() {
    return isset($_SESSION['lpu_current_space']) ? $_SESSION['lpu_current_space'] : NULL;
}

function lpu_spaces_user_login(&$edit, $account) {
    global $user;
    if(is_array($user->roles) && in_array('Médecin', $user->roles)) {
        drupal_goto('space/Médecin');
    }
    if(is_array($user->roles) && in_array('Pharmacien', $user->roles)) {
        drupal_goto('space/Pharmacien');
    }
}


function lpu_spaces__user_logout() {
    global $user;
    if (session_status() == PHP_SESSION_ACTIVE) {
        module_load_include('pages.inc', 'user');
        module_invoke_all('user_logout', $user);
        
        // Destroy the current session, and reset $user to the anonymous user.
        session_destroy();
        
    }
}